In [1]:
# Add the dependencies
import pandas as pd
import os

In [2]:
# Files to load
stats_season_df = pd.read_csv("Resources/Stats_Ht_Season_2003-2019.csv")
player_bio_df = pd.read_csv("Resources/Player_bios.csv")

In [3]:
stats_season_df

,Rk,Player,Ht,Season,Age,Tm,Lg,WS,G,GS,...,BLK,TOV,PF,PTS,FG%,2P%,3P%,eFG%,FT%,TS%
0,1,LeBron James,9-Jun,2008-09,24,CLE,NBA,20.3,81,81,...,93,241,139,2304,0.489,0.535,0.344,0.530,0.780,0.591
1,2,LeBron James,9-Jun,2012-13,28,MIA,NBA,19.3,76,76,...,67,226,110,2036,0.565,0.602,0.406,0.603,0.753,0.640
2,3,Kevin Durant,10-Jun,2013-14,25,OKC,NBA,19.2,81,81,...,59,285,174,2593,0.503,0.549,0.391,0.560,0.873,0.635
3,4,Kevin Durant,10-Jun,2012-13,24,OKC,NBA,18.9,81,81,...,105,280,143,2280,0.510,0.539,0.416,0.559,0.905,0.647
4,5,LeBron James,9-Jun,2009-10,25,CLE,NBA,18.5,76,76,...,77,261,119,2258,0.503,0.560,0.333,0.545,0.767,0.604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8089,8090,Kevin Knox,7-Jun,2018-19,19,NYK,NBA,-1.3,75,57,...,24,114,175,963,0.370,0.387,0.343,0.438,0.717,0.475
8090,8091,Michael Beasley,9-Jun,2012-13,24,PHO,NBA,-1.5,75,20,...,34,144,107,759,0.405,0.426,0.313,0.434,0.746,0.462
8091,8092,Adam Morrison,8-Jun,2006-07,22,CHA,NBA,-1.5,78,23,...,6,130,179,917,0.376,0.391,0.337,0.422,0.710,0.450
8092,8093,Josh Jackson,8-Jun,2018-19,21,PHO,NBA,-1.7,79,29,...,56,173,209,910,0.413,0.445,0.324,0.456,0.671,0.487
8093,8094,Emmanuel Mudiay,3-Jun,2015-16,19,DEN,NBA,-2.1,68,66,...,35,217,141,872,0.364,0.379,0.319,0.404,0.670,0.437

In [4]:
# Drop unnecessary columns from stats_season
stats_season_df = stats_season_df.drop(columns=['Rk', 'Ht', 'Lg'])

In [5]:
stats_season_df.head()

,Player,Season,Age,Tm,WS,G,GS,MP,MPPG,FG,...,BLK,TOV,PF,PTS,FG%,2P%,3P%,eFG%,FT%,TS%
0,LeBron James,2008-09,24,CLE,20.3,81,81,3054,37.704,789,...,93,241,139,2304,0.489,0.535,0.344,0.530,0.780,0.591
1,LeBron James,2012-13,28,MIA,19.3,76,76,2877,37.855,765,...,67,226,110,2036,0.565,0.602,0.406,0.603,0.753,0.640
2,Kevin Durant,2013-14,25,OKC,19.2,81,81,3122,38.543,849,...,59,285,174,2593,0.503,0.549,0.391,0.560,0.873,0.635
3,Kevin Durant,2012-13,24,OKC,18.9,81,81,3119,38.506,731,...,105,280,143,2280,0.510,0.539,0.416,0.559,0.905,0.647
4,LeBron James,2009-10,25,CLE,18.5,76,76,2966,39.026,768,...,77,261,119,2258,0.503,0.560,0.333,0.545,0.767,0.604

In [6]:
# Remove accents from Player names
stats_season_df['Player'] = stats_season_df['Player'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [7]:
# Remove periods from all names
stats_season_df.Player=stats_season_df.Player.str.replace('.','')

In [8]:
stats_season_df

,Player,Season,Age,Tm,WS,G,GS,MP,MPPG,FG,...,BLK,TOV,PF,PTS,FG%,2P%,3P%,eFG%,FT%,TS%
0,LeBron James,2008-09,24,CLE,20.3,81,81,3054,37.704,789,...,93,241,139,2304,0.489,0.535,0.344,0.530,0.780,0.591
1,LeBron James,2012-13,28,MIA,19.3,76,76,2877,37.855,765,...,67,226,110,2036,0.565,0.602,0.406,0.603,0.753,0.640
2,Kevin Durant,2013-14,25,OKC,19.2,81,81,3122,38.543,849,...,59,285,174,2593,0.503,0.549,0.391,0.560,0.873,0.635
3,Kevin Durant,2012-13,24,OKC,18.9,81,81,3119,38.506,731,...,105,280,143,2280,0.510,0.539,0.416,0.559,0.905,0.647
4,LeBron James,2009-10,25,CLE,18.5,76,76,2966,39.026,768,...,77,261,119,2258,0.503,0.560,0.333,0.545,0.767,0.604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8089,Kevin Knox,2018-19,19,NYK,-1.3,75,57,2158,28.773,338,...,24,114,175,963,0.370,0.387,0.343,0.438,0.717,0.475
8090,Michael Beasley,2012-13,24,PHO,-1.5,75,20,1554,20.720,310,...,34,144,107,759,0.405,0.426,0.313,0.434,0.746,0.462
8091,Adam Morrison,2006-07,22,CHA,-1.5,78,23,2326,29.821,355,...,6,130,179,917,0.376,0.391,0.337,0.422,0.710,0.450
8092,Josh Jackson,2018-19,21,PHO,-1.7,79,29,1988,25.165,347,...,56,173,209,910,0.413,0.445,0.324,0.456,0.671,0.487
8093,Emmanuel Mudiay,2015-16,19,DEN,-2.1,68,66,2068,30.412,329,...,35,217,141,872,0.364,0.379,0.319,0.404,0.670,0.437

In [9]:
stats_season_df.to_csv('Resources/stats_season_clean.csv', index=False)

In [10]:
player_bio_df

,Unnamed: 0,player_name,team_abbreviation,age,player_height_cm,player_weight_kg,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Dennis Rodman,CHI,36,198.12,99.79,Southeastern Oklahoma State,USA,1986,2,...,5.7,16.1,3.1,16.1,0.186,0.323,0.100,0.479,0.113,1996-97
1,1,Dwayne Schintzius,LAC,28,215.90,117.93,Florida,USA,1990,1,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
2,2,Earl Cureton,TOR,39,205.74,95.25,Detroit Mercy,USA,1979,3,...,0.8,1.0,0.4,-2.1,0.105,0.102,0.103,0.376,0.148,1996-97
3,3,Ed O'Bannon,DAL,24,203.20,100.70,UCLA,USA,1995,1,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,4,Ed Pinckney,MIA,34,205.74,108.86,Villanova,USA,1985,1,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11155,11155,Lance Thomas,BKN,32,203.20,108.86,Duke,USA,Undrafted,Undrafted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-20
11156,11156,Luc Mbah a Moute,HOU,33,203.20,104.33,UCLA,Cameroon,2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-20
11157,11157,Sindarius Thornwell,NOP,25,195.58,97.52,South Carolina,USA,2017,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-20
11158,11158,Tyler Zeller,SAS,30,213.36,114.76,North Carolina,USA,2012,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-20
11159,11159,Andre Roberson,OKC,28,200.66,95.25,Colorado,USA,2013,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-20

In [11]:
# Drop unnecessary columns
player_bio_df = player_bio_df.drop(columns=['Unnamed: 0'])

In [12]:
# Remove periods from all names
player_bio_df.player_name=player_bio_df.player_name.str.replace('.','')

In [13]:
# Add each suffix to remove to a list.
suffixes = [" Jr."," Sr.", " Jr", " III", " II", " IV", " Sr"]

# Iterate through the words in the "suffixes" list and replace them with an empty space, "".
for word in suffixes:
    player_bio_df["player_name"] = player_bio_df["player_name"].str.replace(word,"")

In [14]:
player_bio_df.head()

,player_name,team_abbreviation,age,player_height_cm,player_weight_kg,college,country,draft_year,draft_round,draft_number,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,Dennis Rodman,CHI,36,198.12,99.79,Southeastern Oklahoma State,USA,1986,2,27,...,5.7,16.1,3.1,16.1,0.186,0.323,0.100,0.479,0.113,1996-97
1,Dwayne Schintzius,LAC,28,215.90,117.93,Florida,USA,1990,1,24,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
2,Earl Cureton,TOR,39,205.74,95.25,Detroit Mercy,USA,1979,3,58,...,0.8,1.0,0.4,-2.1,0.105,0.102,0.103,0.376,0.148,1996-97
3,Ed O'Bannon,DAL,24,203.20,100.70,UCLA,USA,1995,1,9,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,Ed Pinckney,MIA,34,205.74,108.86,Villanova,USA,1985,1,10,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97

In [15]:
# Drop rows from years before 2003-04
player_bio_df = player_bio_df.drop(player_bio_df[player_bio_df.season.isin(["1996-97", "1997-98", "1998-99", "1999-00", "2000-01", "2001-02", "2002-03"])].index)

In [16]:
player_bio_df.to_csv('Resources/player_bio_clean.csv', index=False)

In [17]:
nba_players_df = pd.merge(stats_season_df, player_bio_df,  how='left', left_on=['Player','Season'], right_on = ['player_name','season'])

In [18]:
nba_players_df

,Player,Season,Age,Tm,WS,G,GS,MP,MPPG,FG,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,LeBron James,2008-09,24,CLE,20.3,81,81,3054,37.704,789,...,28.4,7.6,7.2,14.7,0.042,0.189,0.334,0.591,0.365,2008-09
1,LeBron James,2012-13,28,MIA,19.3,76,76,2877,37.855,765,...,26.8,8.0,7.3,14.1,0.044,0.208,0.298,0.640,0.344,2012-13
2,Kevin Durant,2013-14,25,OKC,19.2,81,81,3122,38.543,849,...,32.0,7.4,5.5,8.0,0.022,0.184,0.327,0.635,0.259,2013-14
3,Kevin Durant,2012-13,24,OKC,18.9,81,81,3119,38.506,731,...,28.1,7.9,4.6,12.7,0.018,0.201,0.298,0.647,0.213,2012-13
4,LeBron James,2009-10,25,CLE,18.5,76,76,2966,39.026,768,...,29.7,7.3,8.6,10.8,0.030,0.185,0.333,0.604,0.398,2009-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8097,Kevin Knox,2018-19,19,NYK,-1.3,75,57,2158,28.773,338,...,12.8,4.5,1.1,-13.6,0.025,0.120,0.219,0.475,0.060,2018-19
8098,Michael Beasley,2012-13,24,PHO,-1.5,75,20,1554,20.720,310,...,10.1,3.8,1.5,-11.5,0.038,0.170,0.276,0.462,0.125,2012-13
8099,Adam Morrison,2006-07,22,CHA,-1.5,78,23,2326,29.821,355,...,11.8,2.9,2.1,-7.0,0.026,0.092,0.220,0.450,0.121,2006-07
8100,Josh Jackson,2018-19,21,PHO,-1.7,79,29,1988,25.165,347,...,11.5,4.4,2.3,-9.6,0.032,0.136,0.234,0.487,0.142,2018-19
8101,Emmanuel Mudiay,2015-16,19,DEN,-2.1,68,66,2068,30.412,329,...,12.8,3.4,5.5,-3.7,0.017,0.107,0.253,0.437,0.281,2015-16

In [19]:
# Determine if there are any missing values
nba_players_df.isnull().sum()

Player                  0
Season                  0
Age                     0
Tm                      0
WS                      0
G                       0
GS                      0
MP                      0
MPPG                    0
FG                      0
FGA                     0
2P                      0
2PA                     0
3P                      0
3PA                     0
FT                      0
FTA                     0
ORB                     0
DRB                     0
TRB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
PF                      0
PTS                     0
FG%                    28
2P%                    55
3P%                  1090
eFG%                   28
FT%                   290
TS%                    27
player_name             0
team_abbreviation       0
age                     0
player_height_cm        0
player_weight_kg        0
college                 0
country                 0
draft_year              0
draft_round             0
draft_number            0
gp                     15
pts                    15
reb                    15
ast                    15
net_rating             15
oreb_pct               15
dreb_pct               15
usg_pct                15
ts_pct                 15
ast_pct                15
season                  0
dtype: int64

In [20]:
nba_players_df.to_csv('Resources/nba_players.csv', index=False)