In [4]:
#Import Dependencies
import pandas as pd
from sqlalchemy import create_engine
from config import db_password

In [5]:
db_string = f"postgres://postgres:{db_password}@127.0.0.1:5432/NBA_Draft_db"
engine = create_engine(db_string)

In [6]:
nba_df = pd.read_sql_query('select * from "nba_players_college"',con=engine)
nba_df

,player,season,age,tm,ws,games,gs,mp,mppg,fg,...,cfta,corb,cdrb,ctrb,coast,cstl,cblk,ctov,cpf,cpts
0,Doug McDermott,2014-15,23,CHI,0.0,36,0,321,8.917,43,...,715,281.0,807.0,1088,194,34,14,321.0,265.0,3150
1,Doug McDermott,2017-18,26,TOT,2.3,81,4,1768,21.827,237,...,715,281.0,807.0,1088,194,34,14,321.0,265.0,3150
2,Doug McDermott,2016-17,25,TOT,2.6,66,5,1508,22.848,222,...,715,281.0,807.0,1088,194,34,14,321.0,265.0,3150
3,Doug McDermott,2015-16,24,CHI,2.8,81,4,1861,22.975,291,...,715,281.0,807.0,1088,194,34,14,321.0,265.0,3150
4,Doug McDermott,2018-19,27,IND,2.9,77,1,1340,17.403,207,...,715,281.0,807.0,1088,194,34,14,321.0,265.0,3150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6502,Reggie Williams,2014-15,28,SAS,0.2,20,0,105,5.250,15,...,2,0.0,0.0,0,1,0,0,0.0,1.0,0
6503,Reggie Williams,2012-13,26,CHA,0.3,40,0,380,9.500,57,...,2,0.0,0.0,0,1,0,0,0.0,1.0,0
6504,Reggie Williams,2011-12,25,CHA,0.3,33,13,747,22.636,106,...,2,0.0,0.0,0,1,0,0,0.0,1.0,0
6505,Reggie Williams,2009-10,23,GSW,1.7,24,10,782,32.583,140,...,2,0.0,0.0,0,1,0,0,0.0,1.0,0
6506,Reggie Williams,2010-11,24,GSW,3.7,80,9,1626,20.325,268,...,2,0.0,0.0,0,1,0,0,0.0,1.0,0